import 'dart:io';
import 'dart:math';
import 'dart:ui' as ui show WindowPadding;
import 'package:easy_localization/easy_localization.dart';
import 'package:expense_tracker/reusable_component/toast/flushbar_helper.dart';
import 'package:expense_tracker/utils/common/base_bloc.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:expense_tracker/utils/common/constants.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:shimmer/shimmer.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:path_provider/path_provider.dart';
import 'package:http/http.dart' as http;
import '../theme/colors.dart';
part 'buildcontext_extension.dart';
part 'double_extension.dart';
part 'align_extension.dart';
part 'padding_extension.dart';
part 'text_style_extension.dart';
part 'string_extension.dart';
part 'svg_extension.dart';
part 'shimmer_extension.dart';

//part 'text_input_formatoe_extensions.dart';
